options {
    directory "/var/cache/bind";
    forwarders { 8.8.8.8; };
    dnssec-validation no;
    listen-on { any; };
    listen-on-v6 { none; };
    allow-query { any; };
    recursion yes;
};

zone "family.test" IN {
    type master;
    file "/etc/bind/zones/family.test.zone";
    allow-update { none; };
};

zone "hotel.test" IN {
    type master;
    file "/etc/bind/zones/hotel.test.zone";
    allow-update { none; };
};

zone "payment.test" IN {
    type master;
    file "/etc/bind/zones/payment.test.zone";
    allow-update { none; };
};
